Repository itmo-opd-professional-score/opd-professional-score-frontend, pull requests merged in 2025-04, with the labels that each got.

#24 Feat | Sound simple test implementation
  src/api/resolvers/test/dto/output/simple-sound-test-output.dto.ts
  src/pages/SimpleSoundTest.vue
  src/router/router.ts
Labels: enhancement, important

#25 Feat | Additional Visual Test implementation
  src/components/AdditionalVisualTest.vue
  src/router/router.ts
Labels: enhancement, important

#22 Feat | Test stat card
  src/App.vue
  src/components/TestStatisticsCard.vue
  src/pages/TestResultsPage.vue
Labels: enhancement, important

#31 Refactor | Rewrite User service logic using API Resolver
  eslint.config.js
  src/api/resolvers/auth/auth.resolver.ts
  src/api/resolvers/user/dto/input/user-data-input.dto.ts
  src/api/resolvers/user/dto/output/set-user-role-output.dto.ts
  src/api/resolvers/user/user.resolver.ts
  src/components/RoleSelectForm.vue
  src/components/UserManagerList.vue
  src/pages/PersonalAccount.vue
  src/services/user.ts
  src/utils/userState/UserState.ts
  src/utils/userState/UserState.types.ts
Labels: enhancement, ready for merge, important

#35 Feat/create test block management
  src/api/resolvers/testBlocks/dto/input/create-test-block-input.dto.ts
  src/api/resolvers/testBlocks/dto/output/create-test-block-output.dto.ts
  src/api/resolvers/testBlocks/test-block.resolver.ts
  src/components/AdditionalVisualTest.vue
  src/components/RoleSelectForm.vue
  src/components/TestRowElement.vue
  src/components/UI/AppHeader.vue
  src/components/UserRowElement.vue
  src/pages/CreateTestBlockPage.vue
  src/router/router.ts
Labels: enhancement, important

#37 Fix | Hot fixes
  src/api/resolvers/testBlocks/dto/input/create-test-block-input.dto.ts
  src/api/resolvers/testBlocks/dto/output/create-test-block-output.dto.ts
  src/api/resolvers/testBlocks/test-block.resolver.ts
  src/components/RoleSelectForm.vue
  src/pages/tests/addition/visual/AdditionVisualTest.vue
  src/router/router.ts
Labels: bug

#38 Fix | Link profile changing types with server's
  src/api/resolvers/user/dto/output/update-user-output.dto.ts
  src/pages/PersonalAccountChanging.vue
  src/utils/userState/UserState.ts
  src/utils/userState/UserState.types.ts
Labels: bug

#41 Fix | Rewrite test types state
  src/App.vue
  src/components/TestsManagerList.vue
  src/pages/CreateTestBlockPage.vue
  src/pages/PersonalAccount.vue
  src/store/test-types.store.ts
  src/utils/testTypeState/TestTypeState.ts
  src/utils/testTypeState/TestTypeState.types.ts
Labels: bug, enhancement

#30 Feat | Light Simple Test implementation
  .gitignore
  src/App.vue
  src/pages/tests/LightSimpleTest.vue
  src/router/router.ts
Labels: enhancement, important

#49 Feat | Style fixes & Tests linking #1
  src/api/resolvers/test/dto/input/create-addition-input.dto.ts
  src/api/resolvers/test/dto/output/create-addition-output.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/components/ProfessionsManagerList.vue
  src/components/TestBlocksManagerList.vue
  src/components/TestsManagerList.vue
  src/components/UI/ProfessionsManagerElement.vue
  src/components/UI/TestBlockElement.vue
  src/components/UI/TestManagerElement.vue
  src/components/UI/UserManagerElement.vue
  src/components/UserManagerList.vue
  src/pages/PersonalAccount.vue
  src/pages/tests/addition/sound/AdditionSoundTest.vue
  src/pages/tests/addition/visual/AdditionVisualTest.vue
  src/router/router.ts
Labels: enhancement

#50 Feat | Tests linking #2
  src/api/resolvers/test/dto/input/create-simple-input.dto.ts
  src/api/resolvers/test/dto/input/simple-sound-test-input.dto.ts
  src/api/resolvers/test/dto/output/create-output.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/api/resolvers/user/dto/output/user-data-output.dto.ts
  src/pages/PersonalAccount.vue
  src/pages/tests/LightSimpleTest.vue
  src/pages/tests/TestMapper.vue
  src/pages/tests/TestResultsPage.vue
  src/pages/tests/simple/SimpleLightTest.vue
  src/pages/tests/simple/SimpleSoundTest.vue
  src/router/router.ts
  src/utils/userState/UserState.ts
Labels: enhancement

#52 Feat | Link Tests Results Page
  public/copy.svg
  src/api/dto/tests-scores.dto.ts
  src/api/resolvers/test/dto/output/test-data-output.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/api/resolvers/testType/dto/output/test-type-data-output.dto.ts
  src/api/resolvers/testType/testType.resolver.ts
  src/api/resolvers/user/user.resolver.ts
  src/components/TestStatisticsCard.vue
  src/components/TestsManagerList.vue
  src/components/TestsScoreList.vue
  src/components/UI/CommonButton.vue
  src/components/UI/TestScoreElement.vue
  src/components/UserManagerList.vue
  src/pages/tests/TestResultsPage.vue
  src/router/router.ts
  src/store/test-types.store.ts
  src/utils/userState/UserState.ts
Labels: enhancement

#43 Feat | Simple moving object test
  src/api/resolvers/test/dto/input/create-rdo-input.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/components/ReactionCircle.vue
  src/pages/SimpleReactionTest.vue
  src/pages/tests/simple/SimpleLightTest.vue
  src/router/router.ts
Labels: enhancement, important

#44 Feat | Test Settings window
  src/api/dto/test-settings.dto.ts
  src/pages/SelectSettingsPage.vue
  src/router/router.ts
Labels: enhancement

#29 Feat | Color reaction speed test
  src/components/ColorReactionTest.vue
Labels: enhancement, important

#53 Feat | Filter test results by gender
  src/api/resolvers/auth/auth.resolver.ts
  src/components/TestsScoreList.vue
  src/components/testFilter/TestFilter.vue
  src/components/testFilter/testFilter.types.d.ts
  src/pages/PersonalAccount.vue
  src/pages/PersonalAccountChanging.vue
  src/pages/tests/TestResultsPage.vue
  src/utils/userState/UserState.ts
Labels: enhancement

#55 Feat/hard moving objefix(test): calculating the averagect
  src/components/MultiReactionTest.vue
  src/components/ReactionCircle.vue
  src/pages/HardReactionTest.vue
Labels: enhancement

#59 Feat | Test ScoreList age filter
  src/api/dto/test-settings.dto.ts
  src/components/MultiReactionTest.vue
  src/components/TestsScoreList.vue
  src/components/UI/inputs/CustomInput.vue
  src/components/testFilter/TestFilter.vue
  src/pages/tests/SelectSettingsPage.vue
  src/pages/tests/hard/HardRdoTest.vue
  src/router/router.ts
  src/utils/userState/UserState.types.ts
Labels: enhancement

#60 Feat | verbal test
  src/api/resolvers/test/dto/input/create-cognitive-input.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/pages/tests/cognitive/VerbalTest.vue
  src/pages/tests/types.d.ts
  src/router/router.ts
Labels: enhancement, important

#62 Feat | stroop test
  src/api/resolvers/test/dto/input/create-cognitive.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/pages/tests/cognitive/StroopTest.vue
  src/router/router.ts
Labels: enhancement, important

#68 Feat | numerical series test
  src/api/resolvers/test/test.resolver.ts
  src/pages/tests/cognitive/NumericalSeriesTest.vue
  src/router/router.ts
Labels: enhancement, important

#66 Feat | simple tracking test
  src/App.vue
  src/api/resolvers/test/dto/input/create-tracking-input.dto.ts
  src/api/resolvers/test/test.resolver.ts
  src/pages/tests/simple/SimpleTrackingTest.vue
  src/router/router.ts
Labels: enhancement
